template_path: "sc-tag-options-external.j2"
stack_name: "sc-tag-options-external"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "prod/sc-portfolio-ec2.yaml"
  - "prod/sc-portfolio-ec2-external.yaml"
  - "prod/sc-portfolio-s3-basic.yaml"
sceptre_user_data:
  Departments:
    - "sage-external"
  Projects:
    - "collaborator"
  ProductIDs:
    - !stack_output_external sc-portfolio-ec2-external::SCEC2portfolioId
