language: python
python: 3.6
cache: pip
branches:
  only:
  - develop
  - prod
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install pre-commit sceptre sceptre-ssm-resolver sceptre-date-resolver
stages:
  - name: validate
  - name: deploy
    if: type = push
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - pre-commit autoupdate
        - pre-commit run --all-files
    - stage: deploy
      script:
        # SC-26 & SC-219 workaround: dis-associate and re-associate SC actions on every deploy
        - sceptre delete $TRAVIS_BRANCH/sc-product-assoc-ec2 --yes
        - sceptre launch $TRAVIS_BRANCH --yes
