template_path: remote/peer-route-config.yaml
stack_name: peer-vpn-stridespoolvpc
parameters:
  PeeringConnectionId: "pcx-0631346ea5ff7181c"  # org-sagebase-strides peering connection ID
  VpcPrivateRouteTable: "rtb-08a75564389754ce6" # org-sagebase-strides us-east-1-stridespoolvpc-PrivateRouteTable
  VpcPublicRouteTable: "rtb-0b4cbae079ca85295"  # org-sagebase-strides us-east-1-stridespoolvpc-PublicRouteTable
  VpnCidr: "10.1.0.0/16"       # org-sagebase-admincentral sophos-utm VPN CIDR
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/peer-route-config.yaml --create-dirs -o templates/remote/peer-route-config.yaml"
