Description: Resources for Jumpcloud IDP
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ScipoolprodAdminMetadata:
    Type: String
    Description: "Public certificate for Jumpcloud AWS app"
Resources:
  ScipoolprodAdminSamlProvider:
    Type: Custom::SAMLProvider
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-saml-provider-FunctionArn'
      Name: "scipoolprod-admin"
      Metadata: !Ref ScipoolprodAdminMetadata
      URL: ""
  ScipoolprodAdminSamlProviderRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 28800
      RoleName: !GetAtt ScipoolprodAdminSamlProvider.Name
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref ScipoolprodAdminSamlProvider
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                "SAML:aud": "https://signin.aws.amazon.com/saml"
Outputs:
  ScipoolprodAdminSamlProviderArn:
    Value: !Ref ScipoolprodAdminSamlProvider
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ScipoolprodAdminSamlProviderArn'
  ScipoolprodAdminSamlProviderRoleArn:
    Value: !GetAtt ScipoolprodAdminSamlProviderRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ScipoolprodAdminSamlProviderRoleArn'
