template_path: "sc-ec2-actions.yaml"
stack_name: "sc-ec2-actions"
dependencies:
  - "develop/sc-enduser-iam.yaml"
  - "develop/cfn-cr-sc-actions-provider.yaml"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  AssumeRole: "arn:aws:iam::465877038949:role/SCEC2LaunchRole"
