template_path: "remote/sc-portfolio-ec2.yaml"
stack_name: "sc-portfolio-ec2-external"
dependencies:
  - "develop/sc-ec2vpc-launchrole.yaml"
  - "develop/sc-enduser-iam.yaml"
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/master/ec2/sc-portfolio-ec2-external.yaml --create-dirs -o templates/remote/sc-portfolio-ec2-external.yaml"
